### PR TITLE
Upgrade Agora submodule + vibe.d

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
This works for me.

### CODE REVIEW

**Comment by Geod24** [comment]
I guess we can close this ? Also there's no  Vibe.d upgrade anymore.

**Comment by kchulj** [comment]
> I guess we can close this ? Also there's no Vibe.d upgrade anymore.

Yes this can be closed.

**Comment by kchulj** [comment]
Current version of faucet is not compatible with Agora.
Good news is, it seems to be a simple submodule change.

**Comment by Geod24** [comment]
Superseded by #33

**Pull request closed without merging**
