### PR TITLE
Update Agora to latest version

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
Includes Flash / Schnorr tx support.

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
Need to add a submodule, one sec.

**Comment by AndrejMitrovic** [comment]
Done.

**Review by kchulj — APPROVED** [review]
✅

**Comment by kchulj** [comment]
> @kchulj do you want to test it first or is it ok to merge?

I'll test locally and merge if there are no issues.

**Comment by Geod24** [comment]
image

Credit: https://www.commitstrip.com/

**Pull request merged**
